from __future__ import annotations
from datetime import date
from typing import Optional
from sqlalchemy import String, ForeignKey, Text, Boolean, Integer, Date
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import UUIDTimeStampedModel, CreatedByModel, ApiaryScopedModel


class BeeAgentJob(UUIDTimeStampedModel, CreatedByModel, ApiaryScopedModel):
    """Configures a scheduled Bee-Agent cron job per apiary."""
    __tablename__ = "bee_agent_jobs"

    name: Mapped[str] = mapped_column(String(160), index=True)
    custom_prompt: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Scope: IMKEREI | STANDORT | VOLK
    scope: Mapped[str] = mapped_column(String(20), default="IMKEREI")

    # JSON-serialised list of entity IDs (location or hive IDs), empty = all
    entity_ids: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    include_weather_data: Mapped[bool] = mapped_column(Boolean, default=False)
    include_locations: Mapped[bool] = mapped_column(Boolean, default=True)
    include_hives: Mapped[bool] = mapped_column(Boolean, default=True)
    include_journal_entries: Mapped[bool] = mapped_column(Boolean, default=True)
    include_tasks: Mapped[bool] = mapped_column(Boolean, default=True)
    include_calendar: Mapped[bool] = mapped_column(Boolean, default=True)
    max_journal_entries: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    cron_expression: Mapped[str] = mapped_column(String(64), default="0 8 * * *")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    # SUGGESTION = Co-Pilot (proposals only), AUTO_CREATE = Auto-Pilot (creates tasks)
    execution_mode: Mapped[str] = mapped_column(String(20), default="SUGGESTION")

    # Relationships
    proposals: Mapped[list["BeeAgentProposal"]] = relationship(
        "BeeAgentProposal", back_populates="job", cascade="all, delete-orphan"
    )


class BeeAgentProposal(UUIDTimeStampedModel):
    """A task proposal generated by the Bee-Agent in SUGGESTION mode."""
    __tablename__ = "bee_agent_proposals"

    job_id: Mapped[Optional[str]] = mapped_column(
        ForeignKey("bee_agent_jobs.id", ondelete="SET NULL"), nullable=True, index=True
    )
    apiary_id: Mapped[str] = mapped_column(
        ForeignKey("apiaries.id", ondelete="CASCADE"), index=True
    )

    title: Mapped[str] = mapped_column(String(160))
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    priority: Mapped[str] = mapped_column(String(10), default="MEDIUM")
    due_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)

    location_id: Mapped[Optional[str]] = mapped_column(
        ForeignKey("locations.id", ondelete="SET NULL"), nullable=True
    )
    hive_id: Mapped[Optional[str]] = mapped_column(
        ForeignKey("hives.id", ondelete="SET NULL"), nullable=True
    )

    is_accepted: Mapped[bool] = mapped_column(Boolean, default=False)

    # Relationships
    job: Mapped[Optional["BeeAgentJob"]] = relationship("BeeAgentJob", back_populates="proposals")
