"""add_treatment_models

Revision ID: 2107ad74f26b
Revises: a1b2c3d4e5f6
Create Date: 2026-07-14 08:10:07.265479
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2107ad74f26b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_methods',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_methods_name'), 'treatment_methods', ['name'], unique=True)
    op.create_table('treatments',
    sa.Column('hive_id', sa.String(length=36), nullable=False),
    sa.Column('treatment_method_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('apiary_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['apiary_id'], ['apiaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_method_id'], ['treatment_methods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatments_hive_id'), 'treatments', ['hive_id'], unique=False)
    op.create_index(op.f('ix_treatments_treatment_method_id'), 'treatments', ['treatment_method_id'], unique=False)
    op.create_table('treatment_images',
    sa.Column('treatment_id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_images_treatment_id'), 'treatment_images', ['treatment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_images_treatment_id'), table_name='treatment_images')
    op.drop_table('treatment_images')
    op.drop_index(op.f('ix_treatments_treatment_method_id'), table_name='treatments')
    op.drop_index(op.f('ix_treatments_hive_id'), table_name='treatments')
    op.drop_table('treatments')
    op.drop_index(op.f('ix_treatment_methods_name'), table_name='treatment_methods')
    op.drop_table('treatment_methods')
    # ### end Alembic commands ###
