"""add_honey_batch_dib_ranges

Revision ID: 59eeb84b4bce
Revises: 8e6c4a3b1f92
Create Date: 2026-06-16 08:34:55.130492
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59eeb84b4bce'
down_revision: Union[str, None] = '8e6c4a3b1f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'honey_batch_dib_ranges' not in tables:
        op.create_table('honey_batch_dib_ranges',
        sa.Column('honey_batch_id', sa.String(length=36), nullable=False),
        sa.Column('dib_label_start', sa.String(length=50), nullable=True),
        sa.Column('dib_label_end', sa.String(length=50), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['honey_batch_id'], ['honey_batches.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_honey_batch_dib_ranges_honey_batch_id'), 'honey_batch_dib_ranges', ['honey_batch_id'], unique=False)
    
    # --- DATA MIGRATION UPGRADE ---
    import uuid
    from datetime import datetime, timezone
    columns = [c['name'] for c in inspector.get_columns('honey_batches')]
    if 'dib_label_start' in columns and 'dib_label_end' in columns:
        res = conn.execute(
            sa.text("SELECT id, dib_label_start, dib_label_end FROM honey_batches WHERE dib_label_start IS NOT NULL OR dib_label_end IS NOT NULL")
        ).fetchall()
        
        for row in res:
            batch_id, start, end = row
            now = datetime.now(timezone.utc)
            # Insert into new table only if it doesn't already have entries
            existing_count = conn.execute(
                sa.text("SELECT count(*) FROM honey_batch_dib_ranges WHERE honey_batch_id = :batch_id"),
                {"batch_id": batch_id}
            ).scalar()
            if existing_count == 0:
                conn.execute(
                    sa.text(
                        "INSERT INTO honey_batch_dib_ranges (id, created_at, updated_at, honey_batch_id, dib_label_start, dib_label_end) "
                        "VALUES (:id, :created_at, :updated_at, :honey_batch_id, :dib_label_start, :dib_label_end)"
                    ),
                    {
                        "id": str(uuid.uuid4()),
                        "created_at": now,
                        "updated_at": now,
                        "honey_batch_id": batch_id,
                        "dib_label_start": start,
                        "dib_label_end": end
                    }
                )
    # ------------------------------

    if 'log_session_apiaries' not in tables:
        op.create_table('log_session_apiaries',
        sa.Column('log_session_id', sa.String(length=36), nullable=False),
        sa.Column('apiary_id', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['apiary_id'], ['apiaries.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['log_session_id'], ['log_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('log_session_id', 'apiary_id')
        )
    if 'log_session_hives' not in tables:
        op.create_table('log_session_hives',
        sa.Column('log_session_id', sa.String(length=36), nullable=False),
        sa.Column('hive_id', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['log_session_id'], ['log_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('log_session_id', 'hive_id')
        )
    if 'log_session_locations' not in tables:
        op.create_table('log_session_locations',
        sa.Column('log_session_id', sa.String(length=36), nullable=False),
        sa.Column('location_id', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['log_session_id'], ['log_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('log_session_id', 'location_id')
        )
               
    with op.batch_alter_table('honey_batches', schema=None) as batch_op:
        if 'dib_label_end' in columns:
            batch_op.drop_column('dib_label_end')
        if 'dib_label_start' in columns:
            batch_op.drop_column('dib_label_start')
        
    log_session_columns = [c['name'] for c in inspector.get_columns('log_sessions')]
    if 'scope_type' not in log_session_columns:
        op.add_column('log_sessions', sa.Column('scope_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_sessions', 'scope_type')
               
    conn = op.get_bind()
    columns = [c['name'] for c in sa.inspect(conn).get_columns('honey_batches')]
    with op.batch_alter_table('honey_batches', schema=None) as batch_op:
        if 'dib_label_start' not in columns:
            batch_op.add_column(sa.Column('dib_label_start', sa.String(length=50), nullable=True))
        if 'dib_label_end' not in columns:
            batch_op.add_column(sa.Column('dib_label_end', sa.String(length=50), nullable=True))
            
    # --- DATA MIGRATION DOWNGRADE ---
    res = conn.execute(
        sa.text("SELECT honey_batch_id, dib_label_start, dib_label_end FROM honey_batch_dib_ranges")
    ).fetchall()
    
    updated_batches = set()
    for row in res:
        batch_id, start, end = row
        if batch_id not in updated_batches:
            conn.execute(
                sa.text("UPDATE honey_batches SET dib_label_start = :start, dib_label_end = :end WHERE id = :id"),
                {"start": start, "end": end, "id": batch_id}
            )
            updated_batches.add(batch_id)
    # --------------------------------

    op.drop_table('log_session_locations')
    op.drop_table('log_session_hives')
    op.drop_table('log_session_apiaries')
    op.drop_index(op.f('ix_honey_batch_dib_ranges_honey_batch_id'), table_name='honey_batch_dib_ranges')
    op.drop_table('honey_batch_dib_ranges')
    # ### end Alembic commands ###


