"""add_treatment_application_types

Revision ID: c159853fc0c4
Revises: 2107ad74f26b
Create Date: 2026-07-14 08:58:39.779140
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c159853fc0c4'
down_revision: Union[str, None] = '2107ad74f26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_application_types',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatment_application_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_application_types_name'), ['name'], unique=True)

    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_type_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_treatments_application_type_id'), ['application_type_id'], unique=False)
        batch_op.create_foreign_key('fk_treatments_application_type', 'treatment_application_types', ['application_type_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_treatments_application_type', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_treatments_application_type_id'))
        batch_op.drop_column('application_type_id')

    with op.batch_alter_table('treatment_application_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_application_types_name'))

    op.drop_table('treatment_application_types')
    # ### end Alembic commands ###
